CREATE TABLE reconciliation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    internal_trade_count INTEGER NOT NULL,
    external_trade_count INTEGER NOT NULL,
    matched_count INTEGER NOT NULL,
    exception_count INTEGER NOT NULL
);

CREATE TABLE trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_run_id BIGINT NOT NULL,
    source VARCHAR(16) NOT NULL,
    trade_id VARCHAR(64) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    quantity NUMERIC(19, 6) NOT NULL,
    price NUMERIC(19, 6) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    trade_date DATE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_trades_reconciliation_run
        FOREIGN KEY (reconciliation_run_id)
        REFERENCES reconciliation_runs (id)
);

CREATE INDEX idx_trades_run_trade_id
    ON trades (reconciliation_run_id, trade_id);

CREATE INDEX idx_trades_run_source
    ON trades (reconciliation_run_id, source);

CREATE TABLE reconciliation_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_run_id BIGINT NOT NULL,
    trade_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    description VARCHAR(500) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_results_reconciliation_run
        FOREIGN KEY (reconciliation_run_id)
        REFERENCES reconciliation_runs (id)
);

CREATE INDEX idx_results_run_status
    ON reconciliation_results (reconciliation_run_id, status);

CREATE INDEX idx_results_run_trade_id
    ON reconciliation_results (reconciliation_run_id, trade_id);

CREATE TABLE exception_resolutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_result_id BIGINT NOT NULL,
    resolution_status VARCHAR(32) NOT NULL,
    note VARCHAR(1000) NOT NULL,
    resolved_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_exception_resolutions_result
        FOREIGN KEY (reconciliation_result_id)
        REFERENCES reconciliation_results (id)
);

CREATE INDEX idx_exception_resolutions_result_resolved_at
    ON exception_resolutions (reconciliation_result_id, resolved_at);
