spring.application.name=tradesync-backend
debug=false

spring.datasource.url=${TRADESYNC_DB_URL:jdbc:postgresql://localhost:5432/tradesync}
spring.datasource.username=${TRADESYNC_DB_USERNAME:tradesync}
spring.datasource.password=${TRADESYNC_DB_PASSWORD:tradesync}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health
